
#ifndef RMW_MICROXRCEDDS_CONFIG_H
#define RMW_MICROXRCEDDS_CONFIG_H

#include <uxr/client/config.h>

//#define RMW_UXRCE_TRANSPORT_UDP
//#define RMW_UXRCE_TRANSPORT_TCP
//#define RMW_UXRCE_TRANSPORT_SERIAL
#define RMW_UXRCE_TRANSPORT_CUSTOM
//#define RMW_UXRCE_TRANSPORT_IPV4
//#define RMW_UXRCE_TRANSPORT_IPV6
//#define RMW_UXRCE_USE_REFS
//#define RMW_UXRCE_ALLOW_DYNAMIC_ALLOCATIONS					// "Enables increasing static pools with dynamic allocation when needed."
//#define RMW_UXRCE_GRAPH										// "Allows to perform graph-related operations to the user"
//#define RMW_UROS_ERROR_HANDLING								// "Provides error handling callback functionality to user-space"



#ifdef RMW_UXRCE_TRANSPORT_UDP
    #define RMW_UXRCE_MAX_TRANSPORT_MTU UXR_CONFIG_UDP_TRANSPORT_MTU
    #define RMW_UXRCE_DEFAULT_IP "@RMW_UXRCE_DEFAULT_UDP_IP@"
    #define RMW_UXRCE_DEFAULT_PORT "@RMW_UXRCE_DEFAULT_UDP_PORT@"
#elif defined(RMW_UXRCE_TRANSPORT_TCP)
    #define RMW_UXRCE_MAX_TRANSPORT_MTU UXR_CONFIG_TCP_TRANSPORT_MTU
    #define RMW_UXRCE_DEFAULT_IP "@RMW_UXRCE_DEFAULT_TCP_IP@"
    #define RMW_UXRCE_DEFAULT_PORT "@RMW_UXRCE_DEFAULT_TCP_PORT@"
#elif defined(RMW_UXRCE_TRANSPORT_SERIAL)
    #define RMW_UXRCE_MAX_TRANSPORT_MTU 		3
    #define RMW_UXRCE_DEFAULT_SERIAL_DEVICE "/dev/ttyAMA0"		// "Sets the agent serial port."
#elif defined(RMW_UXRCE_TRANSPORT_CUSTOM)
    #define RMW_UXRCE_MAX_TRANSPORT_MTU UXR_CONFIG_CUSTOM_TRANSPORT_MTU
#endif

#define RMW_UXRCE_ENTITY_CREATION_TIMEOUT 0					// "This value sets the maximum time to wait for an XRCE entity creation in milliseconds. If set to 0 best effort is used."
#define RMW_UXRCE_ENTITY_DESTROY_TIMEOUT 0

//#define RMW_UXRCE_STREAM_HISTORY_INPUT
//#define RMW_UXRCE_STREAM_HISTORY_OUTPUT

#if defined(RMW_UXRCE_STREAM_HISTORY_INPUT) && defined(RMW_UXRCE_STREAM_HISTORY_OUTPUT)
#undef RMW_UXRCE_STREAM_HISTORY_INPUT
#undef RMW_UXRCE_STREAM_HISTORY_OUTPUT
#define RMW_UXRCE_STREAM_HISTORY_INPUT @RMW_UXRCE_STREAM_HISTORY_INPUT@
#define RMW_UXRCE_STREAM_HISTORY_OUTPUT @RMW_UXRCE_STREAM_HISTORY_OUTPUT@
#else
#define RMW_UXRCE_STREAM_HISTORY_INPUT 4
#define RMW_UXRCE_STREAM_HISTORY_OUTPUT 4
#endif

#define RMW_UXRCE_PUBLISH_RELIABLE_TIMEOUT 1000

#define RMW_UXRCE_MAX_HISTORY 8
#define RMW_UXRCE_MAX_INPUT_BUFFER_SIZE (RMW_UXRCE_MAX_TRANSPORT_MTU * RMW_UXRCE_STREAM_HISTORY_INPUT)
#define RMW_UXRCE_MAX_OUTPUT_BUFFER_SIZE (RMW_UXRCE_MAX_TRANSPORT_MTU * RMW_UXRCE_STREAM_HISTORY_OUTPUT)

#define RMW_UXRCE_MAX_SESSIONS 			2
#define RMW_UXRCE_MAX_OPTIONS 			2*3
#define RMW_UXRCE_MAX_NODES 			4
#define RMW_UXRCE_MAX_PUBLISHERS 		4
#define RMW_UXRCE_MAX_SUBSCRIPTIONS 	4
#define RMW_UXRCE_MAX_SERVICES			4
#define RMW_UXRCE_MAX_CLIENTS 			4
#define RMW_UXRCE_MAX_TOPICS 			RMW_UXRCE_MAX_PUBLISHERS + RMW_UXRCE_MAX_SUBSCRIPTIONS + RMW_UXRCE_MAX_NODES
#define RMW_UXRCE_MAX_WAIT_SETS 		4
#define RMW_UXRCE_MAX_GUARD_CONDITION	4

#if RMW_UXRCE_MAX_TOPICS == -1
#define RMW_UXRCE_MAX_TOPICS_INTERNAL RMW_UXRCE_MAX_PUBLISHERS + RMW_UXRCE_MAX_SUBSCRIPTIONS
#else
#define RMW_UXRCE_MAX_TOPICS_INTERNAL RMW_UXRCE_MAX_TOPICS
#endif

#define RMW_UXRCE_NODE_NAME_MAX_LENGTH 	60
#define RMW_UXRCE_TOPIC_NAME_MAX_LENGTH 60
#define RMW_UXRCE_TYPE_NAME_MAX_LENGTH	100

#define RMW_UXRCE_ENTITY_NAMING_BUFFER_LENGTH 100

#endif  // RMW_MICROXRCEDDS_CONFIG_H
